spring:
  main: {
    allow-bean-definition-overriding: true,
    banner-mode: false
  }
  jpa:
    hibernate: {
      ddl-auto: update
    }
    generate: {
      ddl: true
    }
    properties:
      hibernate: {
        dialect: org.hibernate.dialect.SQLServer2012Dialect,
        format_sql: true
      }
      javax.persistence.jdbc.autoCommit: true
    show-sql: true
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    platform: mssql
    url: jdbc:sqlserver://dev6000:1433;DatabaseName=sbomiDB;integratedSecurity=false;encrypt=true;trustServerCertificate=true
    username: ENC(oh4KHRmJbkrgwMi6fB8eE54815FvdfO+Wj1uvXajdQf5SPnVT+TDi/g1adjELnpt)
    password: ENC(zX8Aipex1Mhz84anz+EgDga1tkpSvUKMzglU0T5NuVbUnj9MFDDoYdhPKZiK+KWw)
    initialization-mode: always
    show-sql: true
    hikari: {
      maximum-pool-size: 20,
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    }
url: http://dev6000:3000/tc
uName: infodba
password: ENC(MZMcppLKPE4XjYHyvakE2UDInlwaGb1cFD4dWQ6G6rPJThCS52xqAunoJJWy9z33)
tcMaxRetries: '10'
tcRetryDelay: '1'
transactionFolder: /Users/imranali/Desktop/transaction
logFolder: /Users/imranali/Desktop/transaction/log
updateSchedule: 0 0 * * * *
parallelImport: '2'
maximumErrors: '524'
alwaysClassify: false
searchParallel: '1'
deleteSchedule: 0 0 * * * *
awcUrl: http://dev6000:3000/tcs
app:
  frontend: {
    base-url: '*'
  }
management:
  endpoints:
    web:
      exposure: {
        include: '*'
      }
