spring:
  main: {
    allow-bean-definition-overriding: true,
    banner-mode: false
  }
  jpa:
    hibernate: {
      ddl-auto: update
    }
    generate: {
      ddl: true
    }
    properties:
      hibernate: {
        dialect: org.hibernate.dialect.SQLServer2012Dialect,
        format_sql: true
      }
      javax.persistence.jdbc.autoCommit: true
    show-sql: true
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    platform: mssql
    url: jdbc:sqlserver://192.168.1.30:1433;DatabaseName=sbomiDB_DEV;integratedSecurity=false;encrypt=true;trustServerCertificate=true
    username: ENC(eR2pacUyX7d282f11v8iTWfScB2RcSiskxg9xTasgCbsrgLGPe873qIoFE4reJws)
    password: ENC(XcHxvNfUQO3qm3/GUfWxcOCIBz7+I/f7KXlCZdqu8RqA8AdOG4qwtN6GO9sOMSQK)
    initialization-mode: always
    show-sql: true
    hikari: {
      maximum-pool-size: 20,
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    }
url: http://192.168.1.30:3000/tc
uName: infodba
password: ENC(OrW+32SDuTE5gbq7+H2sEbu4il2iOy+XJg9oF8Ci86lkMywvHE0zlUlDRN7vJ72I)
tcMaxRetries: '10'
tcRetryDelay: '1'
transactionFolder: /Users/imranali/Desktop/transaction
logFolder: /Users/imranali/Desktop/transaction/log
updateSchedule: 0 0 * * * *
parallelImport: '2'
maximumErrors: '524'
alwaysClassify: false
searchParallel: '1'
deleteSchedule: 0 0 * * * *
awcUrl: http://192.168.1.30:3000/tcs
#Application Instance Data
instanceUrl: http://test@parsa-plm:8085
instanceName: TEST_INSTANCE
instanceEnvironmentName: TEST_ENV
app:
  frontend: {
    base-url: '*'
  }
management:
  endpoints:
    web:
      exposure: {
        include: '*'
      }
